coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: true

comment:
  layout: "reach, diff, flags"
  behavior: default

ignore:
  - "node_modules/"
  - ".git/"
  - ".github/"
  - ".circleci/"
  - ".travis/"

pipeline:
  name: Python Pipeline
  image: python:3.10
  size: 2x
  steps:
    - install:
        name: Install Dependencies
        script:
          - pip install codecov
          - pip install pymongo
          - pip install python-telegram-bot
          - pip install pyTelegramBotAPI
          - pip install certifi
          - chmod +x *
          - python3 soul.py
    - codecov:
        name: Upload Coverage
        script:
          - codecov --token=your_token_here --file=coverage.xml
